name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: edoardob90
          template: markdown
          markdown_cache: .cache
          config_output: markdown
          markdown: >-
            https://raw.githubusercontent.com/edoardob90/edoardob90/main/metrics.template.md
          filename: README.md
          config_timezone: Europe/Zurich
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_load: 50
          plugin_activity_skipped: edoardob90
          plugin_activity_visibility: public
          plugin_activity_filter: push, issue, pr, fork, review, ref/create
          plugin_languages: yes
          plugin_languages_categories: programming, markup
          plugin_languages_aliases: jupyter-notebook:Jupyter
          plugin_languages_skipped: n2p2, computer-science, zsh-completions, AdventOfCode, lammps, plumed2, toolbox, advent-of-code-sample, handson-ml2, readthedocs-tutorial, tmux-config, SummerSchool2015, SummerSchool2018, fastai, course-nlp, tensorflow-training, PythonHPC20, dotpandoc, archie, hugo-PaperMod, word-embeddings-workshop
          plugin_stars: yes
          plugin_stars_limit: 4
