name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: edoardob90
          template: markdown
          markdown_cache: .cache
          config_output: markdown
          markdown: >-
            https://raw.githubusercontent.com/edoardob90/edoardob90/main/metrics.template.md
          filename: metrics.output.md
          config_timezone: Europe/Zurich
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, fork, review, ref/create, star
          plugin_languages: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_stars: yes
          plugin_stars_limit: 3
